services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EnMarche\MailerBundle\Transporter\RabbitMQTransporter: ~

    enmarche.mailer.transporter.rmq: '@EnMarche\MailerBundle\Transporter\RabbitMQTransporter'

    EnMarche\MailerBundle\Manager\MailManager:
        public: true
        arguments:
            - '@enmarche.mailer.transporter.default'




