services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EnMarche\MailerBundle\Mailer\Transporter\RabbitMQTransporter: ~

    enmarche.mailer.transporter.rmq: '@EnMarche\MailerBundle\Mailer\Transporter\RabbitMQTransporter'

    EnMarche\MailerBundle\Mailer\Mailer: ~

    EnMarche\MailerBundle\Mail\MailBuilderInterface: '@EnMarche\MailerBundle\Mail\MailBuilder'
